# data.py
# Course data for Coursebot, grounded in real UWFlow ratings + reviews.
# Each entry: "code" (course code) and "text" (grounded description the RAG pipeline embeds).
# 33 courses: core MATH, CS, and STAT for first/second-year math & CS students,
# across the regular, advanced, and enriched streams.

courses = [
    # ===================== MATH =====================
    {
        "code": "MATH 135",
        "text": "MATH 135 is Algebra for Honours Mathematics, the standard first proof-based course for math students. It covers mathematical reasoning and proof, divisibility and the Euclidean algorithm, modular arithmetic, congruences, complex numbers, and polynomials. On UWFlow it has about 79% liked and 44% easy. The main difficulty is the jump into rigorous proofs, which is new for most students coming from high school. Once you adjust to writing proofs it becomes much more manageable. It pairs with MATH 137 (calculus) in 1A. Antirequisite: MATH 145.",
    },
    {
        "code": "MATH 136",
        "text": "MATH 136 is Linear Algebra 1 for Honours Mathematics, taken in 1B after MATH 135. It covers systems of linear equations, matrices, vector spaces, linear transformations, determinants, eigenvalues and eigenvectors. On UWFlow it has about 64% liked and 45% easy, making it slightly harder-feeling than MATH 135. Students describe the learning style as somewhat circular/abstract, and it rewards keeping up with the material. Prerequisite: MATH 135 with at least 60%. This 60% prerequisite is the gate into MATH 235. Antirequisite: MATH 146.",
    },
    {
        "code": "MATH 137",
        "text": "MATH 137 is Calculus 1 for Honours Mathematics, the 1A calculus course. It covers limits, continuity, sequences, derivatives, and an introduction to integration, all developed rigorously. On UWFlow it has about 68% liked and 56% easy. A common warning: despite the familiar-sounding name, it is NOT high-school calculus review — it is rigorous, with real emphasis on limits, sequences, and proof-style reasoning. Antirequisite: MATH 127, MATH 147.",
    },
    {
        "code": "MATH 138",
        "text": "MATH 138 is Calculus 2 for Honours Mathematics, the 1B continuation of MATH 137. It covers integration techniques, applications of integration, sequences and series, and power/Taylor series. On UWFlow it has about 68% liked and 46% easy. Many students find it more enjoyable and intuitive than MATH 137, even though the easy rating is a bit lower. Prerequisite: MATH 137. Antirequisite: MATH 128, MATH 148.",
    },
    {
        "code": "MATH 127",
        "text": "MATH 127 is Calculus 1 for the Sciences, a lighter alternative to MATH 137 taken by science (non-math-major) students. It covers limits, derivatives, and basic integration with less rigor and proof than the honours stream. On UWFlow it has about 53% liked and 50% easy. It's the gentler Calc 1 option. Antirequisite: MATH 137, MATH 147.",
    },
    {
        "code": "MATH 128",
        "text": "MATH 128 is Calculus 2 for the Sciences, the lighter alternative to MATH 138. It covers integration techniques, series, and applications with a more computational, less rigorous approach ('plug and chug'). On UWFlow it has about 58% liked and 53% easy. This is the Calc 2 that some CS students deliberately take instead of MATH 138 to lighten their GPA load, since it's easier than the honours version. Antirequisite: MATH 138, MATH 148.",
    },
    {
        "code": "MATH 147",
        "text": "MATH 147 is Calculus 1 (Advanced Level), the advanced version of MATH 137 for students who want a deeper, real-analysis-flavoured treatment. On UWFlow it has about 93% liked but only 44% easy — hard but loved. It approaches calculus from a rigorous analysis perspective and is widely considered the most approachable of the advanced 145-148 stream. Take it if you love pure math. Antirequisite: MATH 127, MATH 137.",
    },
    {
        "code": "MATH 148",
        "text": "MATH 148 is Calculus 2 (Advanced Level), the advanced version of MATH 138, often described as 'MATH 138 on steroids.' On UWFlow it has about 87% liked and 40% easy — rigorous and demanding but well-regarded. Prerequisite: MATH 147 (or strong MATH 137). Antirequisite: MATH 128, MATH 138.",
    },
    {
        "code": "MATH 145",
        "text": "MATH 145 is Algebra (Advanced Level), the advanced version of MATH 135 and one of the most notoriously difficult first-year courses at Waterloo. It covers algebra and number theory at a much deeper, more abstract level. On UWFlow it has about 95% liked but only 27% easy — the lowest 'easy' rating of any first-year math course, and among the lowest anywhere. It's described as brutal but transformative, with generous curves. Take it only if you genuinely love pure math. Antirequisite: MATH 135.",
    },
    {
        "code": "MATH 146",
        "text": "MATH 146 is Linear Algebra 1 (Advanced Level), the advanced version of MATH 136. It's proof-based and abstract but considered more approachable than MATH 145. On UWFlow it has about 92% liked and 52% easy. Prerequisite: MATH 145 (or strong MATH 135). Antirequisite: MATH 136. It leads to the advanced MATH 245 and CS 245.",
    },
    {
        "code": "MATH 235",
        "text": "MATH 235 is Linear Algebra 2 for Honours Mathematics, the second-year continuation of MATH 136. It covers orthogonal and unitary matrices and transformations, orthogonal projections, the Gram-Schmidt procedure, least-squares and best approximation, inner products, orthogonal diagonalization, and the singular value decomposition with applications. On UWFlow it has a 69% liked rating, 44% easy, and 79% useful across about 540 ratings. Compared to MATH 136 it's less computational and more application- and proof-oriented (spans, orthogonality, etc.), and there's a fair amount of review of 136 material early on. Students who did well in 136 generally find it manageable, and it's fairly prof-dependent — a good instructor who explains the intuition behind theorems makes a big difference. The advice: stay on top of the post-midterm content and keep the computational techniques sharp. Prerequisite: MATH 136 with at least 60% (or MATH 146). Corequisite: MATH 128/138/148. Antirequisite: MATH 245. Leads to AMATH 242, STAT 331, many PMATH and CO courses, and quantum-information courses.",
    },
    {
        "code": "MATH 245",
        "text": "MATH 245 is Linear Algebra 2 (Advanced Level), the advanced version of MATH 235, taken after MATH 146. It's a theory-heavy, coordinate-free treatment covering minimal polynomials, Jordan Canonical Form, inner product spaces, spectral theory and adjoint operators over the reals and complexes, an introduction to functional analysis, and tensor products. On UWFlow it has 88% liked and 90% useful, with 40% easy across about 90 ratings — challenging but very well-regarded. Interestingly, several students call it one of the easiest advanced math courses and even one of the easiest courses they've taken overall, largely because of fair, well-run offerings (e.g. Blake Madill): mostly non-cumulative term tests, group assignments worth only ~10%, and the option to skip the final if you do well on tests. The main demands are memorizing proofs for tests and that it can feel abstract/hard to build intuition depending on the instructor — it's noticeably prof-dependent. It's a strong lead-in to upper-year pure math. Prerequisite: MATH 146; Honours Mathematics students only. Antirequisite: MATH 235, MATH 225. Leads to AMATH 242, many PMATH and CO courses, and quantum-information courses.",
    },
    {
        "code": "MATH 237",
        "text": "MATH 237 is Calculus 3 for Honours Mathematics, the multivariable calculus course covering functions of several variables: limits, continuity, differentiability, the chain rule, the gradient vector and directional derivatives, Taylor's formula, optimization, mappings and the Jacobian, and multiple integrals in various coordinate systems. On UWFlow it has an 81% liked rating, 55% easy, and 86% useful across about 600 ratings — one of the better-liked second-year math courses. It's largely computational and fairly intuitive; many students find it a relatively chill, standard Calc 3 with weekly short quizzes and Mobius assignments (often with unlimited tries), and a final that's about what you'd expect. The main criticism is that it can feel like rote computation with limited intuition or proof, and it's somewhat prof-dependent. Doing the course-note and practice problems is the standard path to a good grade. Prerequisite: one of MATH 136/146 and one of MATH 128 (>=70%)/138 (>=60%)/148; Honours Math or Math/Physics students. Antirequisite: MATH 247, MATH 207, MATH 227. Leads to AMATH 231, AMATH 242, STAT 330, real/complex analysis, and many physics courses.",
    },
    {
        "code": "MATH 247",
        "text": "MATH 247 is Calculus 3 (Advanced Level), the advanced version of MATH 237, taken after MATH 146 and 148. It's a rigorous real-analysis treatment of multivariable calculus: topology of R^n (completeness, open/closed/compact sets, connectivity, continuity), multivariable differential calculus, Riemann integration (Jordan content, Fubini's theorem, change of variables), and the open mapping, inverse function, and implicit function theorems. On UWFlow it has 94% liked and 94% useful, with 40% easy across about 90 ratings — hard but exceptionally beloved. Students repeatedly call it one of the best courses at Waterloo: described as 'three courses shoved into one' (16 weeks of material in 12), with assignments noticeably longer and harder than MATH 148's, but with a uniquely engaged classroom of students taking it out of genuine interest. It's excellent preparation for upper-year analysis. The strong recommendation: take it if you enjoyed the advanced stream and love analysis — it's demanding but transformative. Prerequisite: MATH 146 and MATH 148; Honours Mathematics students only. Antirequisite: MATH 237. Leads to AMATH 231, real and complex analysis, differential geometry, and more.",
    },
    {
        "code": "MATH 239",
        "text": "MATH 239 is Introduction to Combinatorics, a required second-year course covering two halves: graph theory (colourings, matchings, connectivity, planarity) and combinatorial analysis/enumeration (generating series, recurrence relations, binary strings, plane trees). On UWFlow it has a 77% liked rating and 78% useful, but only 30% easy across about 830 ratings — one of the harder core math courses, and frequently cited as one of the toughest second-year terms. The content is well-regarded and interesting, but there's a famously steep early learning curve: building combinatorial intuition and getting comfortable with proofs (especially graph-theory proofs by contradiction or 'longest/shortest path' arguments) in the first few weeks is the key to the course becoming manageable. Many find graph theory easier than enumeration, or vice versa, depending on the student. It connects directly to later CS courses like CS 341 (algorithms). Assignments are fair and you can usually drop your worst two. The advice: don't fall behind early, use office hours, and grind the intuition up front. Prerequisite: (MATH 136 or 146) and (MATH 135 >=60% or MATH 145), or 2A Software Engineering. Antirequisite: MATH 249, MATH 229. Leads to CS 341, CO 342, CO 330, and many combinatorics/optimization courses.",
    },

    # ===================== CS =====================
    {
        "code": "CS 115",
        "text": "CS 115 is Introduction to Computer Science 1, the gentlest entry point into CS, aimed at students with little or no programming background. It teaches the fundamentals through functional-style programming in Racket (DrRacket): function definition and application, tracing via substitution, the design recipe (design/testing/documentation), recursive data definitions, lists, trees, and functional/data abstraction. On UWFlow it has only a 27% liked rating, 12% easy, and 22% useful across about 2,300 ratings — among the lowest-rated intro courses, but the ratings need context. The low scores mostly reflect frustration with Racket (a teaching language nobody uses in industry) and the design recipe (which students find tedious — often taking longer than writing the actual code), not that the course is conceptually hard. If you've programmed before, it's widely described as 'free'/very easy; if you're brand new, it's a real introduction and quite self-teachable from the online modules. Note: it's a non-major intro stream — math/CS majors take CS 135 instead. CS 115 leads into CS 116, then CS 136. No prerequisites. Antirequisite: CS 135/137/138/145 and most faculty intro-programming courses.",
    },
    {
        "code": "CS 116",
        "text": "CS 116 is Introduction to Computer Science 2, the continuation of CS 115 in the non-major intro stream. It builds on CS 115's patterns while transitioning from functional Racket to an imperative language (Python): generative and structural recursion, mutation/assignment, primitive types, basic file and console I/O, sequencing, selection, and looping. On UWFlow it has a 79% liked rating, 75% easy, and 89% useful across about 400 ratings — a dramatic jump in satisfaction from CS 115 (27% liked), driven largely by the switch to Python, which students find far more motivating and practically useful than Racket. It's considered an easy, chill course if you keep up with lectures and don't fall behind; the concepts are a bit harder than 115 and assignments can be tedious/long, and the design recipe is still required and still marked strictly. The midterm and final are generally fair. One recurring caution in reviews: academic-integrity (Policy 71) enforcement is strict, so document your work and write code on the official platform. Prerequisite: CS 115 or CS 135 or CS 145. Antirequisite: CS 136/137/138/146 and other faculty intro courses. Leads to CS 136, CS 234, CS 230, and many applied computing courses.",
    },
    {
        "code": "CS 135",
        "text": "CS 135 is Designing Functional Programs, the standard first CS course for math and CS majors (the version most CS students actually take, not CS 115). It introduces computer science through functional programming in Racket: syntax and semantics of a functional language, tracing via substitution, the design recipe (design/testing/documentation), linear and nonlinear data structures, recursive data definitions, abstraction and encapsulation, and generative/structural recursion. On UWFlow it has an 86% liked rating, 67% easy, and 84% useful across about 1,100 ratings — very well-liked despite teaching Racket (which students joke is useless in industry but defend as a good teaching language; 'Racket is overhated' is a common refrain). A key, repeatedly-stated warning: the course starts easy but the difficulty spikes noticeably after the midterm / after the WD (withdrawal) deadline, introducing many new topics — so don't be lulled early, never skip lectures (you can't catch up), and do the assignments yourself rather than using AI, since the exams test exactly that practice. Memorizing contract/template formats and stepper rules pays off on exams. No prerequisites. Antirequisite: CS 115/137/138/145. Leads to CS 136, CS 116, CS 234, and the rest of the CS core.",
    },
    {
        "code": "CS 145",
        "text": "CS 145 is Designing Functional Programs (Advanced Level), the advanced version of CS 135, famously taught by Troy Vasiga and beloved. It speedruns the CS 135 material and then goes deeper into theoretical functional programming: special forms of recursion, lambda calculus, interpreters, and lazy evaluation (Lazy Racket). On UWFlow it has an 80% liked rating, 59% easy, and 70% useful across about 320 ratings — harder than CS 135 by a meaningful amount but more fun, and notably it drops the design recipe (which students count as a plus). The assignments are time-consuming and difficult (some later ones genuinely interesting), while the exams are much more straightforward and follow course content closely. Two important cautions from reviews: unlike some advanced courses, CS 145 is NOT generously curved, so your mark may end up lower than the 135 version would have — and the withdrawal deadline is before the midterm, so if you can't do the assignments without heavy help, decide early. Take it if you want a deeper, more theoretical, more rewarding intro and don't mind a real time commitment. No prerequisites. Antirequisite: CS 115/135/137/138. Leads to CS 136, CS 146, and beyond.",
    },
    {
        "code": "CS 136",
        "text": "CS 136 is Elementary Algorithm Design and Data Abstraction, the second core CS course after CS 135, where the language switches from Racket to C (an imperative language). It introduces algorithm design and analysis, information management, and the C memory model: the first half covers C, memory, pointers and arrays; the second half covers modularization, time complexity, dynamic memory allocation, and basic data structures — iterative and recursive sorting, lists, stacks, queues, trees, and abstract data types (ADTs) and their implementations. On UWFlow it has an 80% liked rating, 57% easy, and a very high 92% useful across about 870 ratings — students consistently rate it as important/foundational even when they find it hard. It's the course where C, pointers, and dynamic memory first seriously test you, and it's widely seen as a real step up in difficulty from 135. Assignments are time-consuming but the exams are often considered fair (sometimes a 'free' final). Common advice: do the assignments yourself (academic-integrity enforcement is strict, including hidden anti-LLM traps), and lean on the fact that midterm/exam questions often mirror past assignments and in-class exercises. Must be taken with the CS 136L lab co-requisite. Prerequisite: CS 145, or >=90% in CS 115, or >=70% in CS 116, or >=60% in CS 135. Antirequisite: CS 137/138/146. Leads to CS 241, CS 245, CS 246, CS 240, and the rest of second-year CS.",
    },
    {
        "code": "CS 136L",
        "text": "CS 136L is Tools and Techniques for Software Development, a 0.25-unit lab course taken alongside CS 136 (it's a required co-requisite). It's a fully online, weekly module-plus-assignment course teaching the practical software-development toolchain: the Linux command-line shell, version control (Git), shell scripting and task automation, writing test cases, tracing and debugging strategies, build automation (Makefiles), and using IDE support for all of the above. On UWFlow it has a 73% liked rating, 74% easy, and 89% useful across about 290 ratings. The consensus: genuinely useful, industry-relevant fundamentals that every CS student needs ('you NEED this class for any further CS'), but tedious, a bit boring, somewhat outdated in places, and broad rather than deep. Light workload (~2 hours/week) and easy if you keep up, though some labs are time-consuming and the in-person labs are mostly optional Q&A sessions. Prerequisite: same as CS 136 (CS 145 / >=90% CS 115 / >=70% CS 116 / >=60% CS 135). Co-requisite: CS 136 or CS 146. Leads to CS 241, CS 246.",
    },
    {
        "code": "CS 146",
        "text": "CS 146 is Elementary Algorithm Design and Data Abstraction (Advanced Level), the advanced version of CS 136, famously taught by Brad Lushman. It speedruns the CS 136 material and then goes far deeper into how programming languages actually work: the differences between functional and imperative paradigms, proof of correctness and Hoare logic, and building interpreters, compilers, and assemblers for a sequence of toy languages (SIMPL, PRIMPL/A-PRIMPL) plus real low-level languages (MMIX assembly). It uses imperative Racket, C, and Haskell. On UWFlow it has a 91% liked rating, 89% useful, but only 44% easy across about 190 ratings — very beloved but genuinely hard. It covers substantially more than CS 136 (often three lectures/week, including a mandatory tutorial-lecture) and has a notorious post-midterm difficulty spike where the pace and language-juggling intensify; missing lectures sets you back fast. Assignments swing between easy and very hard, but there are generous curves, resubmission policies, and bonus marks, and the compiler/assembler assignments are many students' favourites. It overlaps meaningfully with CS 241 material, giving an early look at how programs are translated and executed. Note you can reach it via CS 135->146 (without CS 145) and that path is manageable. As with the other advanced courses, your grade may come out lower than the CS 136 version, but the depth of understanding is widely called worth it. Prerequisite: CS 145 with at least 75%. Co-requisite: CS 136L. Antirequisite: CS 116/136/137/138. Leads to CS 241, CS 245, CS 246, CS 240.",
    },
    {
        "code": "CS 240",
        "text": "CS 240 is Data Structures and Data Management, a core second-year CS course on the design, analysis, and performance of data structures. Topics include priority queues and heaps, AVL trees, sorting, skip lists, hashing, dictionaries, tries, and data structures for text/string processing (pattern matching). On UWFlow it has a 59% liked rating, 56% easy, and 63% useful across about 840 ratings — one of the more divisive core courses. The consistent theme in reviews: the first few modules (expected/average runtime analysis, the proof-heavy/mathematical reasoning portion) are brutal and the hardest part of the course, and the early assignments are notoriously hard; but the second half (the actual data structures and string matching) is more concrete and many students find it interesting and career-useful (it helps with LeetCode). It's quite prof-dependent, and assessments can be unforgiving — some programming questions use hidden private tests where one bug fails everything. Standard advice: push through the rough proof-heavy start, do the assignments, and the back half rewards you. Important prerequisite note: CS 240 requires CS 245 AND one of CS 241/246/247 AND one of STAT 230/240 — so it sits after several second-year courses, not immediately after CS 136. Honours CS, Data Science, BCFM, and SE students only. Antirequisite: CS 234, CS 240E, ECE 250. Leads to CS 341 (algorithms), CS 348, CS 350, CS 360, and much of upper-year CS.",
    },
    {
        "code": "CS 241",
        "text": "CS 241 is Foundations of Sequential Programs, the core second-year course on how high-level languages relate to the underlying computer architecture. It covers basic machine architecture, assembly languages (MIPS, now ARMv8 in newer offerings), assemblers, the specification and translation of programming languages, linkers and loaders, block-structured languages, and parameter-passing mechanisms. The defining feature is a term-long project: across roughly 8 assignments you build a compiler from scratch for a simplified C-like language, going through scanning, parsing, semantic analysis, and code generation. On UWFlow it has an 87% liked rating, 54% easy, and a high 89% useful across about 650 ratings — one of the most beloved and most career-useful CS courses, frequently called the best for understanding how programs actually work at a low level. The main pain point is the assignments: they're long (some require up to ~1000 lines of code), build on each other, and are graded pass/fail against hidden private tests with no handmarking, so a single elusive bug can fail an assignment despite huge effort — but public tests make 100% achievable once it works. Universal advice: start every assignment early (especially the last 2-3), and lean on the legendarily good course notes. Exams are generally fair/easier than the assignments and resemble tutorial problems more than the compiler project. Great if you like systems, C++, or low-level programming. Prerequisite: CS 138, or (CS 246/246E and CS 136L), or (CS 136L and >=85% in CS 136 or CS 146); Honours CS, Data Science, BCFM, SE only. Antirequisite: CS 230, CS 241E, ECE 351. Leads to CS 240, CS 247, CS 350, CS 360, and most upper-year systems courses.",
    },
    {
        "code": "CS 241E",
        "text": "CS 241E is Foundations of Sequential Programs (Enriched), the enriched version of CS 241, taught by Ondrej Lhotak and exceptionally well-regarded. Like CS 241 you build a compiler from scratch, but here you use Scala to compile 'Lacs' (a simplified Scala) down to MIPS, and the compiler is more ambitious — supporting type checking, closures, tail-recursion optimization, and garbage collection (Cheney's algorithm). It's taught bottom-up (starting from machine code and assembly, then the stack, expressions, procedure calls, register allocation via graph colouring, closures, scanning, CYK parsing, type checking, and GC), versus CS 241's more top-down ordering and LR parsing. On UWFlow it has a 94% liked rating, 92% useful, and 46% easy across about 126 ratings — even more beloved than CS 241 (87%), and many call it one of the best-designed courses they've taken at Waterloo. The assignments are mostly 'fill-in-the-blank' / rigid (you complete a scaffolded compiler), which most students prefer to CS 241's open-ended pass/fail grind, though a couple are time-consuming and one tends to stump people, and debugging can dominate. Ondrej's course notes are repeatedly called phenomenal — lectures are nearly optional. Exams are generally fair/easy ('e means easy'). Strongly recommended over CS 241 if you're eligible. Prerequisite: (CS 136L and >=85% in CS 136 or CS 146) or >=85% in CS 138; Honours CS, Data Science, BCFM, SE only. Antirequisite: CS 230, ECE 351. Leads to CS 240, CS 247, CS 350, CS 360.",
    },
    {
        "code": "CS 245",
        "text": "CS 245 is Logic and Computation, a required course (taken by both CS and math students) on logic as a tool for representation, reasoning, and computation. It covers propositional and predicate (first-order) logic, formal deduction, formalizing correct vs incorrect reasoning, defining what is computable, the limits of computation, Turing machines, and Godel's Incompleteness Theorem, with applications to computer science. On UWFlow it has only a 30% liked rating, 54% easy, and a very low 26% useful across about 780 ratings — one of the most disliked core courses in the entire CS program. The dislike is mostly about delivery and organization, not the underlying ideas: students often find the early logic/formal-deduction material genuinely interesting and the proofs no harder than MATH 135's, but complain heavily about bloated/recycled lecture slides, poor organization, dry computational proof-grinding in the back half, and unfair/brutal exams (one recent term had a ~60% final median and had to drop the exam pass threshold from 50% to 45%). It's frequently called one of the most skippable-lecture courses — most people learn from the slides/notes. Treat it as a get-through-it requirement: do the assignments, don't skip the midterm, and lean on the notes. Prerequisite: (one of CS 136/138/146) and (MATH 135 or 145); Honours Mathematics students only. Antirequisite: CS 245E, PMATH 330, SE 212. Leads to CS 240, CS 341, CS 442, ECE 351.",
    },
    {
        "code": "CS 245E",
        "text": "CS 245E is Logic and Computation (Enriched), the enriched version of CS 245. It covers the same three pillars — propositional logic, first-order logic, and computation (Turing machines, Godel's Incompleteness Theorems) — but skips much of the tedious formal-proof 'slop' of regular CS 245 (e.g. the Peano-axiom formal proofs) to reach more interesting advanced content faster. On UWFlow it has a 78% liked rating, 56% easy, and 50% useful across about 50 ratings — a massive improvement over regular CS 245 (30% liked). Reviews are clear that it's essentially a Pure Math course in disguise (a 'math course disguised as CS'), and that it's both more interesting AND often easier-feeling than the regular section, with shorter, more reasonable assignments (3-4 hours each) and a gentler midterm — though finals tend to be long and hard but generously curved. The logic portions help you reason about mathematical proofs in other courses; the computation portion (Turing machines, Godel) is the trickier, more abstract part. Strongly recommended over CS 245 if you're eligible and like theoretical/proof-based material. Prerequisite: >=85% in CS 136 or CS 146; Honours Mathematics students only. Antirequisite: CS 245, PMATH 330, SE 212. Leads to CS 240, CS 341, CS 442.",
    },
    {
        "code": "CS 246",
        "text": "CS 246 is Object-Oriented Software Development, the core course where you learn OOP and modern C++ through a term-long software project. It covers designing, coding, debugging, testing, and documenting medium-sized programs: reading specs and designing software, choosing data/control structures, writing reusable code, basic performance, debuggers, and test suites. On UWFlow it has a 66% liked rating, 57% easy, and 70% useful across about 860 ratings. The strong consensus: it's one of the most practically useful CS courses (C++ is highly valued in industry and co-op), and the project teaches you the most, but there's a freakish amount of content, the assignments are time-consuming and rely on secret/hidden test cases (so you must write your own tests), and the 'C++ trivia' on the midterm feels unnecessary to many. Midterm averages run low (low 60s) but assignments and the project boost grades. Universal advice: find a good project group BEFORE enrolling, start assignments early, don't skip lecture (notes often aren't posted — use the student-made GitHub notes), and write good test cases. Note CS 136L was historically folded into this course. Prerequisite: (CS 146 and CS 136L) or >=60% in CS 138 or (CS 136L and >=60% in CS 136); Honours Math only. Antirequisite: CS 246E, CS 247. Leads to CS 240, CS 241, CS 350, and most SE courses.",
    },
    {
        "code": "CS 246E",
        "text": "CS 246E is Object-Oriented Software Development (Enriched), the enriched version of CS 246, taught by Brad Lushman in his signature notes-driven style. It uses modern C++ (C++20) to give a deep, developer's-eye treatment of OOP and how C++ actually works under the hood: the Big Five, copy/move constructors, RAII and memory management, implementing unique_ptr/vector/string (including short-string optimization), virtual tables, runtime vs compile-time polymorphism, exception handling and noexcept, iterators, template metaprogramming and constexpr, allocators, EBO, and custom memory pools. On UWFlow it has a 94% liked rating, 92% useful, but only 32% easy across about 85 ratings — one of the most loved CS courses, and also one of the harder ones (notably lower 'easy' than regular CS 246's 57%). It covers about 1.5x the content of CS 246, but Lushman's notes are excellent and the assessments are on the easier/more-lenient side (4 assignments ~50%, weekly quizzes ~5%, ~20% midterm with a high median, no final but a ~25% final project). The recurring themes: it teaches genuinely deep, interview-relevant C++ ('writing C++ is easy, writing good C++ is hard'), assignments require perseverance/testing more than cleverness (secret tests again), and the final project is large (4K+ lines) so start early. Definite recommendation over regular CS 246 if eligible. Prerequisite: CS 136L and >=85% in CS 136 or CS 146; Honours Math only. Antirequisite: CS 246. Leads to CS 240, CS 241, CS 350, SE courses.",
    },

    # ===================== STAT =====================
    {
        "code": "STAT 230",
        "text": "STAT 230 is Probability, the core second-year probability course taken by math, CS, and stats students. It introduces probability models: sample spaces, mutually exclusive and independent events, conditional probability and Bayes' Theorem; the named distributions (Discrete Uniform, Hypergeometric, Binomial, Negative Binomial, Geometric, Poisson, Continuous Uniform, Exponential, Normal, Multinomial); discrete and continuous random variables, joint/marginal/conditional distributions, functions of random variables, means/variances/covariances, indicator variables, and the Central Limit Theorem. On UWFlow it has a 59% liked rating, 57% easy, and a high 81% useful across about 1,000 ratings. The defining pattern across reviews: it starts gently (early content feels like a formalization of high-school probability) but gets humbling fast, and the recurring warning is DON'T LET YOUR GUARD DOWN — midterms are often easy-to-fair but finals have a reputation for being brutal (medians get curved). Multi-select multiple-choice makes assessments harder than they look. The back half (continuous RVs, CLT, normal) clicks for many and the content is rated very useful. Standard advice: grind throughout the term to bank marks before the final, and don't underestimate it. Prerequisite: a calc course (MATH 137/147 >=80%, or MATH 128 >=60%, or MATH 138/148); Honours Math/Phys only. Antirequisite: STAT 220, STAT 240. Leads to STAT 231, STAT 330, CS 240, and most stats/ML courses.",
    },
    {
        "code": "STAT 231",
        "text": "STAT 231 is Statistics, the core course following STAT 230, covering a systematic approach to empirical problem solving: critically assessing sampling protocols and whether causal conclusions are justified, connecting population attributes to the named distributions from STAT 230, numerical/graphical data summary and model-fit checking, the method of maximum likelihood for point and interval estimates, hypothesis testing, interpreting confidence intervals and p-values, the Chi-squared and t distributions, likelihood ratio tests, contingency tables, and Gaussian models including two-sample Gaussian and simple linear regression. On UWFlow it has only a 40% liked rating, 49% easy, and 63% useful across about 810 ratings — fairly disliked, though several reviewers call it overhated and easier than STAT 230. The common complaints: it feels like 'plug and chug' / speed-calculating into your calculator with a giant cheat sheet, the course notes are long and not great, assignments use R which isn't really taught (you figure it out), and the experience is 'low cortisol class, high cortisol final.' But it's also widely called genuinely useful, and it's very prof-dependent (Michael Wallace is repeatedly singled out as excellent). Treat it as a useful-but-tedious requirement; pick a good prof if you can. Prerequisite: a calc course (MATH 118/119/128/138/148) and (STAT 220 >=70% or STAT 230 or STAT 240); Honours Math/Phys. Antirequisite: STAT 221, STAT 241. Leads to a huge range of stats, ML, econ, and finance courses.",
    },
    {
        "code": "STAT 240",
        "text": "STAT 240 is Probability (Advanced Level), the advanced/enriched version of STAT 230. It covers the same probability foundations (named distributions, random variables, expectation, CLT) but with more depth and some advanced content toward the end. On UWFlow it has a 78% liked rating, 52% easy, and 81% useful across about 67 ratings — more liked than regular STAT 230 (59%) and considered more interesting, though reviews note most of the genuinely 'advanced' material only appears in the last few weeks while the midterms are essentially harder STAT 230 problems. It's heavily prof-dependent and several offerings are grade-by-exam-only (no assignments, just midterms + final), which some students dislike since it means cramming; difficulty/curving can swing wildly term to term but is generally curved to a reasonable advanced-course average. Most reviewers say it's modestly worth taking over STAT 230 if you like the subject, but if you can only take one advanced course in a term, weigh it against the others. Prerequisite: (MATH 137/147 >=80%) or (MATH 138/148); Honours Mathematics only. Antirequisite: STAT 220, STAT 230. Leads to STAT 231/241, STAT 330, CS 240, and stats/ML courses.",
    },
    {
        "code": "STAT 241",
        "text": "STAT 241 is Statistics (Advanced Level), the advanced/enriched version of STAT 231. Compared to STAT 231 it develops much more of the underlying theory of statistical inference: derivations of statistical tests (rather than plug-and-chug), likelihood ratio testing, the Neyman-Pearson Lemma, the Cramer-Rao lower bound, the EM (expectation-maximization) algorithm, and Bayesian statistics — topics usually reserved for higher-level courses. On UWFlow it has an 89% liked rating, 91% useful, and 43% easy across about 63 ratings — far more loved and rated far more useful than regular STAT 231 (40% liked, 63% useful), at the cost of being harder. Reviews are enthusiastic: it gives a genuinely deep understanding of WHY statistical tests work, midterms/finals are fair and resemble class examples, and several students who disliked STAT 240 or were lukewarm on stats say STAT 241 convinced them statistics is actually cool. It uses some multivariable calculus (partial derivatives, multiple integrals, Lagrange multipliers) even though MATH 237 isn't a formal prereq. Strongly recommended over STAT 231 if you're eligible and want depth. Prerequisite: (MATH 138/148) and (STAT 230 or STAT 240); Honours Math only. Antirequisite: STAT 221, STAT 231. Leads to STAT 330, STAT 331, and the full range of stats/ML/econ/finance courses.",
    },
]